apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {{ .Values.model.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: vllm
    model: {{ .Values.model.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-nemotron-mini-runtime
      storageUri: {{ .Values.model.modelUri }}
      name: ''
      args:
        - --served-model-name={{ .Values.model.servedModelName }}
        {{- if .Values.model.vllmArgs }}
        {{- range .Values.model.vllmArgs }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
      resources:
        limits:
          {{- toYaml .Values.model.resources.limits | nindent 10 }}
        requests:
          {{- toYaml .Values.model.resources.requests | nindent 10 }}
      {{- if .Values.model.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.model.nodeSelector | nindent 8 }}
      {{- end }}
    {{- if .Values.model.tolerations }}
    tolerations:
      {{- toYaml .Values.model.tolerations | nindent 6 }}
    {{- end }}
