{{- $root := . }}
{{- range $name, $model := .Values.models }}
{{- if $model.enabled }}
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {{ $name }}
  namespace: {{ $root.Values.global.namespace }}
  labels:
    app: vllm
    model: {{ $name }}
    chart: {{ $root.Chart.Name }}-{{ $root.Chart.Version }}
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-runtime
      storageUri: {{ $model.modelUri }}
      name: ''
      args:
        - --model={{ $model.modelUri }}
        - --served-model-name={{ $model.servedModelName }}
        {{- if $model.vllmArgs }}
        {{- range $model.vllmArgs }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
      resources:
        limits:
          {{- toYaml $model.resources.limits | nindent 10 }}
        requests:
          {{- toYaml $model.resources.requests | nindent 10 }}
      {{- if $model.nodeSelector }}
      nodeSelector:
        {{- toYaml $model.nodeSelector | nindent 8 }}
      {{- end }}
    {{- if $model.tolerations }}
    tolerations:
      {{- toYaml $model.tolerations | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
