{{- if and .Values.huggingfaceToken.value (not .Values.huggingfaceToken.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: huggingface-token
  namespace: {{ .Values.global.namespace }}
  labels:
    app: vllm
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
stringData:
  token: {{ .Values.huggingfaceToken.value }}
{{- end }}
